import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { test, expect, type Page } from '@playwright/test'

/**
 * Interaction-performance spec (benchmark harness, not a correctness suite).
 *
 * Seeds deterministic scenarios (small/medium/large/stress, generated by
 * `bench/gen-fixtures.ts` from `bench/scenarios.ts`) and measures, in the browser:
 *
 *  - `simulate()` calls executed during representative interactions (drag a new
 *    event from the carousel; drag an existing graph marker);
 *  - long tasks (> 50ms) observed during those interactions;
 *  - end-to-end wall time of the drag gesture.
 *
 * The counters come from `window.__NWV_SIM_STATS__` (dev-server only, see main.tsx).
 *
 * Assertions are deliberately tolerant (structure/bounds, not microsecond flakiness):
 * a drag should never run one full simulation per pointer step, and no interaction
 * should produce a > 250ms long task even for the stress scenario.
 */

const NWV_STORAGE_KEY = 'networth-visualizer-state-v1'

const SPEC_DIR = path.dirname(fileURLToPath(import.meta.url))

function loadFixture(name: string): { events: unknown[]; months: number } {
  const raw = readFileSync(
    path.join(SPEC_DIR, '..', 'bench', 'fixtures', `${name}.json`),
    'utf8',
  )
  return JSON.parse(raw) as { events: unknown[]; months: number }
}

async function seedScenario(page: Page, fixtureName: string) {
  const fixture = loadFixture(fixtureName)
  await page.addInitScript(
    ({ key, events, months }) => {
      try {
        localStorage.setItem(
          key,
          JSON.stringify({
            events,
            projectionYears: Math.round(months / 12),
            currency: 'USD',
            lang: 'en',
            graphSettings: {
              showRealValues: false,
              showLinearReference: false,
              showMonteCarlo: false,
              showAssetBreakdown: false,
              stressTestActive: false,
              showLifeTimeline: true,
              graphTooltipOffset: { x: 0, y: 0 },
              graphTooltipWidth: 260,
              graphTooltipHeight: 320,
              zoomRange: null,
            },
          }),
        )
      } catch {
        /* ignore */
      }
    },
    { key: NWV_STORAGE_KEY, events: fixture.events, months: fixture.months },
  )
  await page.goto('/')
  await expect(page.getByTestId('net-worth-chart')).toBeVisible({ timeout: 30_000 })
  await page.waitForFunction(
    () => document.querySelectorAll('[data-nw-graph-marker]').length > 0,
    undefined,
    { timeout: 30_000 },
  )
}

async function readSimStats(page: Page): Promise<{ calls: number; months: number }> {
  return page.evaluate(() => {
    const s = (window as unknown as { __NWV_SIM_STATS__?: { calls: number; months: number } })
      .__NWV_SIM_STATS__
    return { calls: s?.calls ?? 0, months: s?.months ?? 0 }
  })
}

function installLongTaskObserver(page: Page) {
  return page.evaluate(() => {
    const wins: { startTime: number; duration: number }[] = []
    const win = window as unknown as { __NWV_LONG_TASKS__?: typeof wins }
    win.__NWV_LONG_TASKS__ = wins
    if (typeof PerformanceObserver !== 'undefined') {
      try {
        const obs = new PerformanceObserver((list) => {
          for (const e of list.getEntries()) {
            wins.push({ startTime: e.startTime, duration: e.duration })
          }
        })
        obs.observe({ entryTypes: ['longtask'] })
        ;(win as unknown as { __NWV_LT_OBS__?: PerformanceObserver }).__NWV_LT_OBS__ = obs
      } catch {
        /* longtask unsupported */
      }
    }
  })
}

async function dragFromCarousel(page: Page, dropXRatio: number, steps: number) {
  // Open the investment editor so a draggable icon exists (matches graph.spec flow).
  await page.getByRole('tab', { name: /investment/i }).click()
  const dragBtn = page.getByRole('button', {
    name: /drag onto chart to add or move this event on the timeline/i,
  })
  await expect(dragBtn).toBeVisible()
  const drop = page.getByTestId('nw-graph-drop-zone')
  const src = await dragBtn.boundingBox()
  const dst = await drop.boundingBox()
  expect(src).not.toBeNull()
  expect(dst).not.toBeNull()
  const x = dst!.x + dst!.width * dropXRatio
  const y = dst!.y + dst!.height / 2
  await page.mouse.move(src!.x + src!.width / 2, src!.y + src!.height / 2)
  await page.mouse.down()
  await page.mouse.move(x, y, { steps })
  await page.mouse.up()
}

async function dragFirstGraphMarker(page: Page, dx: number, steps: number) {
  const marker = page.locator('[data-nw-graph-marker]').first()
  await expect(marker).toBeVisible()
  const box = await marker.boundingBox()
  expect(box).not.toBeNull()
  const x0 = box!.x + box!.width / 2
  const y0 = box!.y + box!.height / 2
  await page.mouse.move(x0, y0)
  await page.mouse.down()
  await page.mouse.move(x0 + dx, y0, { steps })
  await page.mouse.up()
}

test.describe('interaction performance (benchmark)', () => {
  for (const scenario of ['medium', 'large', 'stress'] as const) {
    test(`${scenario}: carousel drag does not re-run the engine per pointer step`, async ({
      page,
    }) => {
      await seedScenario(page, scenario)
      await installLongTaskObserver(page)

      const before = await readSimStats(page)
      const t0 = Date.now()
      await dragFromCarousel(page, 0.65, 24)
      const elapsed = Date.now() - t0
      const after = await readSimStats(page)

      const simsDuringDrag = after.calls - before.calls
      // 24 pointer steps cross ~24 month columns; the shared preview simulates at most
      // once per month change (dev adds StrictMode double-render overhead). The old
      // architecture ran 3-4 full simulations per step (~90-100 for this gesture) — a
      // regression to that pattern must fail here.
      console.log(
        `[perf:${scenario}] carousel drag: ${simsDuringDrag} sims / ${elapsed}ms wall`,
      )
      expect(simsDuringDrag, 'simulations per 24-step drag').toBeLessThanOrEqual(44)

      const longTasks = await page.evaluate(
        () => (window as unknown as { __NWV_LONG_TASKS__?: { duration: number }[] })
          .__NWV_LONG_TASKS__ ?? [],
      )
      const worst = Math.max(0, ...longTasks.map((t) => t.duration))
      console.log(`[perf:${scenario}] carousel drag long tasks: ${longTasks.length}, worst ${worst.toFixed(1)}ms`)
      expect(worst).toBeLessThanOrEqual(350)
    })

    test(`${scenario}: marker drag preview is bounded`, async ({ page }) => {
      await seedScenario(page, scenario)
      await installLongTaskObserver(page)

      const before = await readSimStats(page)
      const t0 = Date.now()
      await dragFirstGraphMarker(page, 180, 24)
      const elapsed = Date.now() - t0
      const after = await readSimStats(page)

      const simsDuringDrag = after.calls - before.calls
      console.log(
        `[perf:${scenario}] marker drag: ${simsDuringDrag} sims / ${elapsed}ms wall`,
      )
      // Deferred previews coalesce during fast gestures; bound generously to catch
      // per-step immediate × 2 regressions without flaky micro-thresholds.
      expect(simsDuringDrag, 'simulations per 24-step marker drag').toBeLessThanOrEqual(72)

      const longTasks = await page.evaluate(
        () => (window as unknown as { __NWV_LONG_TASKS__?: { duration: number }[] })
          .__NWV_LONG_TASKS__ ?? [],
      )
      const worst = Math.max(0, ...longTasks.map((t) => t.duration))
      console.log(`[perf:${scenario}] marker drag long tasks: ${longTasks.length}, worst ${worst.toFixed(1)}ms`)
      expect(worst).toBeLessThanOrEqual(350)
    })
  }
})
